config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # https://...amazonaws.com/index入力してenterを押すとtop_controllerの中にあるactionを実行する
    # get '/index', to: 'top#index'
    # E https://...amazonaws.com と入力してenterを押すとtop_controllerの中にあるactionを実行するように変更
    root :to => 'top#index'
    get '/reward', to:'top#reward'
    get '/service', to:'top#service'
    get '/approach', to:'top#approach'
    get '/company', to:'top#company'
    get '/contact', to:'top#contact'
    get '/index', to:'inheritance#index'
    get '/representative', to:'top#representative'
    get '/consultation', to:'consultation#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultation_controller.rb
class ConsultationController < ApplicationController
    def consultation
    end
end

app/controllers/inheritance_controller.rb
class InheritanceController < ApplicationController
    def index
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end
    def reward
    end
    def service
    end
    def approach
    end
    def company
    end 
    def contact
    end
    def representative
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultation_helper.rb
module ConsultationHelper
end

app/helpers/inheritance_helper.rb
module InheritanceHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/consultation/index.html.erb
<div id="wrapper">

  <header id="header">
			<h1>濱村会計事務所</h1>
      <!-- ロゴ -->
		<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="60" height="60" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '60x60', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
		<!-- / ロゴ -->
		<!-- 電話番号+受付時間 -->
		<div class="info">
			<p class="tel"><span>電話:</span> 03-5717-9301</p>
			<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
		</div>
		<!-- / 電話番号+受付時間 -->
	</header>

	<!-- メインナビゲーション -->
  <nav id="mainNav">
  	<a class="menu" id="menu"><span>MENU</span></a>
		<div class="panel">   
    	<ul>
    	<!--	<li><a href="index.html"><strong>トップページ</strong><span>Top</span></a></li> -->
    		<li>
    			<%= link_to root_path, target: "_blank" do %>
					<strong>トップページ</strong><span>Top</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>サービス概要</strong><span>Service</span></a></li> -->
			<li>
    			<%= link_to service_path, target: "_blank" do %>
					<strong>サービス概要</strong><span>Service</span>
					<% end %>
    		</li>
				<!-- <li><a href="subpage.html"><strong>弊社の取り組み</strong><span>Approach</span></a></li> -->
				<li>
    			<%= link_to approach_path, target: "_blank" do %>
					<strong>弊社の取り込み</strong><span>Approach</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>会社情報</strong><span>Company</span></a></li> -->
			<li>
    			<%= link_to company_path, target: "_blank" do %>
					<strong>会社情報</strong><span>Company</span>
					<% end %>
    		</li>
    		<!--	<li><a href="goaisatu.html"><strong>ごあいさつ</strong><span>Greeting</span></a></li> -->
			<li>
    			<%= link_to reward_path, target: "_blank" do %>
					<strong>報酬規定</strong><span>Reward</span>
					<% end %>
    		</li>
    		<li>
    			<%= link_to representative_path, target: "_blank" do %>
					<strong>代表のご挨拶</strong><span>Representative</span>
					<% end %>
    		</li>
				<!-- <li class="last"><a href="subpage.html"><strong>お問い合わせ</strong><span>Contact</span></a></li> -->
				<li class="last">
    			<%= link_to contact_path, target: "_blank" do %>
					<strong>お問い合わせ</strong><span>Contact</span>
					<% end %>
    		</li>
			</ul>   
    </div>
  </nav>
  <!-- / メインナビゲーション -->
  
  <!-- コンテンツ -->
	<section id="main">
  
  	<!-- メイン画像 -->
		<div id="mainBanner">
		<!--	<img src="images/mainImg2.jpg" width="709" height="140" alt=""> -->
		<%= image_tag 'service/mainImg2', :size => '709x140' %>
    	<div class="slogan">
				<h2>自然との調和を目指す企業です</h2>
				<p>革新的な技術で世の中を動かす企業を目指します。</p>
			</div>
		</div>
		<!-- / メイン画像 -->
    
    <section class="content">
    	<h3 class="heading">ホームページサンプル株式会社の取り組み</h3>
      <article>
		<!--	<img src="images/sample1.jpg" width="217" height="140" alt="" class="alignright border" /> -->
				
			<p class = "float_left">幅広いご相談に対応できますが、中でも「融資対策」と「新規法人の設立支援」に関しては強い事務所です。
			融資に関しましては、とにかく実績があります。銀行が好む会社作りからお手伝い致します。
			新規設立におきましては、一貫したサポートが強みです。何をしたら良いのか全くわからないという方でも、お気軽にご相談
			下さい。当事務所では、設立登記や商業登記に加え、税務申告や役員変更のアドバイスを含め、今後を視野に入れたサポートが
			可能です。経験・知識を踏まえ、最適なご提案を致します。もちろん、他の事務所様より移ってきた方でも大丈夫です。同じ
			ように現状を踏まえ、今後を見据えたバックアップをさせて頂きます。今まで、何のアドバイスも無く、言われるがままだ
			った方は、当事務所にご依頼頂くと、驚かれると思います。お客様の現状に合わせ、具体的な説明を行います。料金面、
			サービスの質を見て頂くと、うちの事務所以外に、ここまで行う事務所は無いのではないかとも思う程です。
			相続・事業承継も対応でき、飲食業や製造業、医療法人、公益法人等、あらゆる業種に実績がある事務所です。
			お気軽にご相談下さい。</p>
			<%= image_tag 'consultation/father1.jpg', :size => '217x140', class: 'float_right' %>
    	</article>
    </section>
    
    <section class="content">
			<h3 class="heading">ホームページサンプル株式会社の取り組み</h3>
      <article>
		<!--	  <img src="images/sample2.jpg" width="217" height="140" alt="" class="alignleft border" /> -->
			  
				<p class = "float_left">営業エリアは、東京・埼玉・神奈川がメインとなります。営業時間は、
				９：００～１７：００で、土日祝日はお休みとしておりますが、お客様商売ですので、要望に応じて柔軟に対応しております。</p>
				<%= image_tag 'consultation/father2.jpg', :size => '217x140', class: 'float_right' %>
		</section>
    
		<section class="content">
			<h3 class="heading">会社概要</h3>
      <article>
				<table class="table">
				<tr>
					<th>会社名</th>
					<td>濱村会計事務所</td>
				</tr>
				<tr>
					<th>設立</th>
					<td>平成10年1月10日</td>
				</tr>
				<tr>
					<th>事業内容</th>
					<td>税理・相続</td>
				</tr>
				<tr>
					<th>住所</th>
					<td>〒158-0097 東京都世田谷区用賀３丁目１３−７</td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td>03-5717-9301</td>
				</tr>
				<tr>
					<th>メールアドレス</th>
					<td>info@example.com</td>
				</tr>
				</table>
    	</article>
		</section>
    

    
	</section>
	<!-- / コンテンツ -->

	<aside id="sidebar">
       
		<h3 class="heading">革新的な技術</h3>
    <article>
			<ul>
				<li><a href="subpage.html">トップページ</a></li>
				<li><a href="subpage.html">サービス概要</a></li>
				<li><a href="subpage.html">弊社の取り組み</a></li>
				<li><a href="subpage.html">会社情報</a></li>
				<li><a href="subpage.html">報酬規定</a></li>
				<li><a href="subpage.html">お問い合わせ</a></li>
			</ul>
    </article>
    
	<!--	<h3 class="heading">ホームページサンプル</h3>
    <article>
			<ul>
				<li><a href="subpage.html">環境への取り組みについての説明ページです</a></li>
				<li><a href="subpage.html">ecoキャンペーン開催中です</a></li>
				<li><a href="subpage.html">オフィスの移転に関して</a></li>
				<li><a href="subpage.html">最新商品のご紹介</a></li>
				<li><a href="subpage.html">新規サービスを開始しました</a></li>
				<li><a href="subpage.html">環境賞受賞に関してはこちらをご確認ください</a></li>
			</ul>
     </article>
    
		<h3 class="heading">ホームページサンプル</h3>
		<article>
			<ul class="list">
				<li><a href="subpage.html"><img src="images/thumb1.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
				<li><a href="subpage.html"><img src="images/thumb2.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
				<li><a href="subpage.html"><img src="images/thumb3.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
      </ul> 
		</article>
			<p><a href="subpage.html"><img src="images/side_banner.jpg" width="187" height="63" alt="" class="border" /></a></p> -->
    
	</aside>
 
	<!-- フッター -->
	<footer id="footer">
		<!-- 左側 -->
		<div id="info" class="grid">
			<!-- ロゴ -->
			<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="60" height="60" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '60x60', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
			<!-- / ロゴ -->
			<!-- 電話番号+受付時間 -->
			<div class="info">
				<p class="tel"><span>電話:</span> 03-5717-9301</p>
				<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
			</div>
			<!-- / 電話番号+受付時間 -->
		</div>  
		<!-- / 左側 -->
		<!-- 右側 ナビゲーション -->
		<ul class="footnav">
			<li><a href="subpage.html">報酬規定</a></li>
			<li><a href="subpage.html">無料相談</a></li>
			<li><a href="subpage.html">サービス概要</a></li>
			<li><a href="subpage.html">会社情報</a></li>
			<li><a href="subpage.html">お問い合わせ</a></li>
            <li><a href="subpage.html">求人</a></li>
			<li><a href="subpage.html">サイトマップ</a></li>
		</ul>
		<!-- / 右側 ナビゲーション -->
	</footer>
	<!-- / フッター -->
	<address>Copyright(c) 2013 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank" rel="nofollow">http://f-tpl.com</a></address>
</div>

app/views/top/company.html.erb
<div id="wrapper">

  <header id="header">
			<h1>濱村会計事務所</h1>
      <!-- ロゴ -->
		<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="60" height="60" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '60x60', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
		<!-- / ロゴ -->
		<!-- 電話番号+受付時間 -->
		<div class="info">
			<p class="tel"><span>電話:</span> 03-5717-9301</p>
			<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
		</div>
		<!-- / 電話番号+受付時間 -->
	</header>

	<!-- メインナビゲーション -->
  <nav id="mainNav">
  	<a class="menu" id="menu"><span>MENU</span></a>
		<div class="panel">   
    	<ul>
    	<!--	<li><a href="index.html"><strong>トップページ</strong><span>Top</span></a></li> -->
    		<li>
    			<%= link_to root_path, target: "_blank" do %>
					<strong>トップページ</strong><span>Top</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>サービス概要</strong><span>Service</span></a></li> -->
			<li>
    			<%= link_to service_path, target: "_blank" do %>
					<strong>サービス概要</strong><span>Service</span>
					<% end %>
    		</li>
				<!-- <li><a href="subpage.html"><strong>弊社の取り組み</strong><span>Approach</span></a></li> -->
				<li>
    			<%= link_to approach_path, target: "_blank" do %>
					<strong>弊社の取り込み</strong><span>Approach</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>会社情報</strong><span>Company</span></a></li> -->
			<li>
    			<%= link_to company_path, target: "_blank" do %>
					<strong>会社情報</strong><span>Company</span>
					<% end %>
    		</li>
    		<!--	<li><a href="goaisatu.html"><strong>ごあいさつ</strong><span>Greeting</span></a></li> -->
			<li>
    			<%= link_to reward_path, target: "_blank" do %>
					<strong>報酬規定</strong><span>Reward</span>
					<% end %>
    		</li>
    		<li>
    			<%= link_to representative_path, target: "_blank" do %>
					<strong>代表のご挨拶</strong><span>Representative</span>
					<% end %>
    		</li>
				<!-- <li class="last"><a href="subpage.html"><strong>お問い合わせ</strong><span>Contact</span></a></li> -->
				<li class="last">
    			<%= link_to contact_path, target: "_blank" do %>
					<strong>お問い合わせ</strong><span>Contact</span>
					<% end %>
    		</li>
			</ul>   
    </div>
  </nav>
  <!-- / メインナビゲーション -->
  
  <!-- コンテンツ -->
	<section id="main">
  
  	<!-- メイン画像 -->
		<div id="mainBanner">
		<!--	<img src="images/mainImg2.jpg" width="709" height="140" alt=""> -->
		<%= image_tag 'service/mainImg2', :size => '709x140' %>
    	<div class="slogan">
				<h2>自然との調和を目指す企業です</h2>
				<p>革新的な技術で世の中を動かす企業を目指します。</p>
			</div>
		</div>
		<!-- / メイン画像 -->
    
    <section class="content">
    	<h3 class="heading">ホームページサンプル株式会社の取り組み</h3>
      <article>
		<!--	<img src="images/sample1.jpg" width="217" height="140" alt="" class="alignright border" /> -->
				<%= image_tag 'service/sample1.jpg', :size => '217x140' %>
			<p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす。革新的な技術で世の中を動かす。</p>
    	</article>
    </section>
    
    <section class="content">
			<h3 class="heading">ホームページサンプル株式会社の取り組み</h3>
      <article>
		<!--	  <img src="images/sample2.jpg" width="217" height="140" alt="" class="alignleft border" /> -->
			  <%= image_tag 'service/sample2.jpg', :size => '217x140' %>
				<p>革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
				<p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす。革新的な技術で世の中を動かす。</p>
      </article>
		</section>
    
		<section class="content">
			<h3 class="heading">会社概要</h3>
      <article>
				<table class="table">
				<tr>
					<th>会社名</th>
					<td>ホームページサンプル株式会社（英語表記 Homepage sample Inc.）</td>
				</tr>
				<tr>
					<th>設立</th>
					<td>平成10年1月10日</td>
				</tr>
				<tr>
					<th>事業内容</th>
					<td>税理・相続</td>
				</tr>
				<tr>
					<th>住所</th>
					<td>〒158-0097 東京都世田谷区用賀３丁目１３−７</td>
				</tr>
				<tr>
					<th>電話番号</th>
					<td>03-5717-9301</td>
				</tr>
				<tr>
					<th>メールアドレス</th>
					<td>info@example.com</td>
				</tr>
				</table>
    	</article>
		</section>
    

    
	</section>
	<!-- / コンテンツ -->

	<aside id="sidebar">
       
		<h3 class="heading">革新的な技術</h3>
    <article>
			<ul>
				<li><a href="subpage.html">トップページ</a></li>
				<li><a href="subpage.html">サービス概要</a></li>
				<li><a href="subpage.html">弊社の取り組み</a></li>
				<li><a href="subpage.html">会社情報</a></li>
				<li><a href="subpage.html">報酬規定</a></li>
				<li><a href="subpage.html">お問い合わせ</a></li>
			</ul>
    </article>
    
		<h3 class="heading">ホームページサンプル</h3>
    <article>
			<ul>
				<li><a href="subpage.html">環境への取り組みについての説明ページです</a></li>
				<li><a href="subpage.html">ecoキャンペーン開催中です</a></li>
				<li><a href="subpage.html">オフィスの移転に関して</a></li>
				<li><a href="subpage.html">最新商品のご紹介</a></li>
				<li><a href="subpage.html">新規サービスを開始しました</a></li>
				<li><a href="subpage.html">環境賞受賞に関してはこちらをご確認ください</a></li>
			</ul>
     </article>
    
		<h3 class="heading">ホームページサンプル</h3>
		<article>
			<ul class="list">
				<li><a href="subpage.html"><img src="images/thumb1.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
				<li><a href="subpage.html"><img src="images/thumb2.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
				<li><a href="subpage.html"><img src="images/thumb3.jpg" width="42" height="42" alt=""></a>サンプル株式会社では最新技術と自然との調和を目指します。</li>
      </ul> 
		</article>
			<p><a href="subpage.html"><img src="images/side_banner.jpg" width="187" height="63" alt="" class="border" /></a></p>
    
	</aside>
 
	<!-- フッター -->
	<footer id="footer">
		<!-- 左側 -->
		<div id="info" class="grid">
			<!-- ロゴ -->
			<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="60" height="60" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '60x60', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
			<!-- / ロゴ -->
			<!-- 電話番号+受付時間 -->
			<div class="info">
				<p class="tel"><span>電話:</span> 03-5717-9301</p>
				<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
			</div>
			<!-- / 電話番号+受付時間 -->
		</div>  
		<!-- / 左側 -->
		<!-- 右側 ナビゲーション -->
		<ul class="footnav">
			<li><a href="subpage.html">報酬規定</a></li>
			<li><a href="subpage.html">無料相談</a></li>
			<li><a href="subpage.html">サービス概要</a></li>
			<li><a href="subpage.html">会社情報</a></li>
			<li><a href="subpage.html">お問い合わせ</a></li>
            <li><a href="subpage.html">求人</a></li>
			<li><a href="subpage.html">サイトマップ</a></li>
		</ul>
		<!-- / 右側 ナビゲーション -->
	</footer>
	<!-- / フッター -->
	<address>Copyright(c) 2013 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank" rel="nofollow">http://f-tpl.com</a></address>
</div>

app/views/top/index.html.erb
<div id="wrapper">

  <header id="header">
			<h1>濱村会計事務所</h1>
      <!-- ロゴ -->
		<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="60" height="60" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '60x60', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
		<!-- / ロゴ -->
		<!-- 電話番号+受付時間 -->
		<div class="info">
			<p class="tel"><span>電話:</span> 03-5717-9301</p>
			<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
		</div>
		<!-- / 電話番号+受付時間 -->
	</header>

	<!-- メインナビゲーション -->
  <nav id="mainNav">
  	<a class="menu" id="menu"><span>MENU</span></a>
		<div class="panel">   
    	<ul>
    	<!--	<li><a href="index.html"><strong>トップページ</strong><span>Top</span></a></li> -->
    		<li>
    			<%= link_to root_path, target: "_blank" do %>
					<strong>トップページ</strong><span>Top</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>サービス概要</strong><span>Service</span></a></li> -->
			<li>
    			<%= link_to service_path, target: "_blank" do %>
					<strong>サービス概要</strong><span>Service</span>
					<% end %>
    		</li>
				<!-- <li><a href="subpage.html"><strong>弊社の取り組み</strong><span>Approach</span></a></li> -->
				<li>
    			<%= link_to approach_path, target: "_blank" do %>
					<strong>弊社の取り込み</strong><span>Approach</span>
					<% end %>
    		</li>
			<!--	<li><a href="subpage.html"><strong>会社情報</strong><span>Company</span></a></li> -->
			<li>
    			<%= link_to company_path, target: "_blank" do %>
					<strong>会社情報</strong><span>Company</span>
					<% end %>
    		</li>
    		<!--	<li><a href="goaisatu.html"><strong>ごあいさつ</strong><span>Greeting</span></a></li> -->
			<li>
    			<%= link_to reward_path, target: "_blank" do %>
					<strong>報酬規定</strong><span>Reward</span>
					<% end %>
    		</li>
    		<li>
    			<%= link_to representative_path, target: "_blank" do %>
					<strong>代表のご挨拶</strong><span>Representative</span>
					<% end %>
    		</li>
				<!-- <li class="last"><a href="subpage.html"><strong>お問い合わせ</strong><span>Contact</span></a></li> -->
				<li class="last">
    			<%= link_to contact_path, target: "_blank" do %>
					<strong>お問い合わせ</strong><span>Contact</span>
					<% end %>
    		</li>
			</ul>   
    </div>
  </nav>
  <!-- / メインナビゲーション -->
  
  <!-- メイン画像 -->
	<div id="mainBanner">
		<!--<img src="images/mori6.jpg" alt="">-->
		<%= image_tag 'top/mori6.jpg' %>
        <div class="slogan">
			<h2>税理士事務所</h2>
			<p>濱村会計事務所では相続をスムーズにこなします。<br>相手のことを考える企業を目指しています。</p>
		</div>
	</div>
	<!-- / メイン画像 -->

  <!-- 3カラム -->
  <section class="gridWrapper">
      <article class="grid">
        <div class="box">
         <!-- <img src="images/top_m1.jpg" width="260" height="113" alt=""> -->
         <%= image_tag 'top/top_m1.jpg', :size => '260x113' %>
          <h3>相続について</h3>
          <p>相続のご相談はこのリンクをクリックしてください</p>
          <p class="readmore">
          	
          	<!--<a href="subpage.html">詳細を確認する</a>-->
          	<%= link_to '詳細を確認する', index_path %>
          	</p>
        </div>
      </article>
      <article class="grid">
        <div class="box">
       <!-- <img src="images/top_m2.jpg" width="260" height="113" alt=""> -->
       <%= image_tag 'top/top_m2.jpg', :size => '260x113' %>
          <h3>無料相談</h3>
          <p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
          <p class="readmore">
          	
          	<!--<a href="subpage.html">詳細を確認する</a>-->
          	<%= link_to '詳細を確認する', consultation_path %>
          	</p>
        </div>
      </article>
      <article class="grid">
        <div class="box">
         <!-- <img src="images/top_m3.jpg" width="260" height="113" alt=""> -->
         <%= image_tag 'top/top_m3.jpg', :size => '260x113' %>
          <h3>他社との違い</h3>
          <p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
          <p class="readmore">
          	
          	<!--<a href="subpage.html">詳細を確認する</a>-->
          	<%= link_to '詳細を確認する', root_path %>
          	</p>
        </div>
      </article>
	</section>
	<!-- / 3カラム -->
 
	<!-- フッター -->
	<footer id="footer">
		<!-- 左側 -->
		<div id="info" class="grid">
			<!-- ロゴ -->
			<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" width="45" height="45" alt="Sample site" /><p>濱村会計事務所<span>お悩み解決します</span></p></a>-->
			<%= link_to root_path, target: "_blank" do %>
			<%= image_tag 'top/logo.png', :size => '45x45', :alt => 'Sample site' %><p>濱村会計事務所<span>お悩み解決します</span></p>
			<% end %>
		</div>
			<!-- / ロゴ -->
			<!-- 電話番号+受付時間 -->
			<div class="info">
				<p class="tel"><span>電話:</span> 03-5717-9301</p>
				<p class="open">受付時間: 平日 AM 10:00 〜 PM 19:00</p>
			</div>
			<!-- / 電話番号+受付時間 -->
		</div>  
		<!-- / 左側 -->
		<!-- 右側 ナビゲーション -->
	<!--	<ul class="footnav">
			<li><a href="subpage.html">税務・相続</a></li>
			<li><a href="subpage.html">無料相談</a></li>
			<li><a href="subpage.html">サービス概要</a></li>
			<li><a href="subpage.html">会社情報</a></li>
			<li><a href="subpage.html">お問い合わせ</a></li>
            <li><a href="subpage.html">求人</a></li>
			<li><a href="subpage.html">サイトマップ</a></li>
		</ul> -->
		<!-- / 右側 ナビゲーション -->
	</footer>
	<!-- / フッター -->
	<address>Copyright(c) 2013 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank" rel="nofollow">http://f-tpl.com</a></address>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>